---
version: '3'
services:
  example_hugo:
    container_name: example_hugo
    image: klakegg/hugo:ext-alpine-onbuild
    restart: always
    env_file:
      - hugo.env
    volumes:
      - "./site:/src"
      - "./html:/target"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=false"
    command: --watch
  example_www:
    container_name: example_www
    image: nginx:latest
    restart: always
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.example.entrypoints=http"
      - "traefik.http.routers.example.rule=Host(`example.com`)"
      - "traefik.http.routers.example-secure.entrypoints=https"
      - "traefik.http.routers.example-secure.rule=Host(`example.com`)"
      - "traefik.http.routers.example-secure.tls=true"
    networks:
      - traefik
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./html:/var/www/html:ro"
  example_sn2ssg_py:
    container_name: example_sn2ssg_py
    image: toozej/sn2ssg-py:latest
    restart: always
    volumes:
      - "./site/content/post:/out"
    env_file:
      - sn2ssg-py.env
    labels:
      - "traefik.enable=false"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  traefik:
    external: true
